services:
  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    networks:
      - microservices-network

  order-service:
    build: ./order-service/order-service
    ports:
      - "8082:8082"
    networks:
      - microservices-network
    depends_on:
      - user-service

networks:
  microservices-network:
    driver: bridge
